version: '3'

# docker container rm -f $(docker container ls -aq) && docker volume prune -f

services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: reddit
    ports:
      - '3306:3306'
    volumes:
      - './db_tables/:/docker-entrypoint-initdb.d/'